# docker-compose.yml
version: "3.7"
services:
  webclient:
    build: ./webclient
    ports:
      - 3001:3000
    volumes:
      - ./webclient/src:/app/src
      - ./webclient/public:/app/public
    environment:
      - NODE_ENV=development
    tty: true
